server:
  port: 8081
  host: '0.0.0.0'

kafka:
  brokers: 'kafka:9092'
  topic: 'gps-data'
  group_id: 'gps-processor'
  min_bytes: 10000
  max_bytes: 10000000
  partition: 0
  protocol_version: '3.0.0'

logging:
  level: 'info'
  format: 'json'
