version: '3.8'

services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: processor
    ports:
      - '8081:8081'
    environment:
      - PROCESSOR_SERVER_PORT=8081
      - PROCESSOR_SERVER_HOST=0.0.0.0
      - PROCESSOR_KAFKA_BROKERS=kafka:9092
      - PROCESSOR_KAFKA_TOPIC=gps-data
      - PROCESSOR_KAFKA_GROUP_ID=gps-processor
      - PROCESSOR_KAFKA_PROTOCOL_VERSION=3.5.0
      - PROCESSOR_LOGGING_LEVEL=info
      - PROCESSOR_LOGGING_FORMAT=json
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-network
