version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gps-producer
    networks:
      - kafka-network
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          "import socket; socket.gethostbyname('host.docker.internal')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  kafka-network:
    name: kafka-network
    external: true
